<a href="https://colab.research.google.com/github/rkp74/Word_Embedding/blob/main/Word_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
sent = [ 'the glass of tea' , 'the glass of coffee' , 'the cup of milk' , "I am good boy" , "I am good Software Developer" , "Understand the meaning of words" , " Your videos are good",]

In [15]:
sent

['the glass of tea',
 'the glass of coffee',
 'the cup of milk',
 'I am good boy',
 'I am good Software Developer',
 'Understand the meaning of words',
 ' Your videos are good']

In [16]:
voc_size = 12000

In [17]:
onehot_repr = [one_hot(words,voc_size ) for words in sent]

In [18]:
print(onehot_repr)

[[633, 5093, 11577, 4266], [633, 5093, 11577, 9303], [633, 10095, 11577, 5810], [3645, 913, 4036, 9932], [3645, 913, 4036, 5461, 8984], [10943, 633, 7436, 11577, 4424], [5310, 10730, 3755, 4036]]


In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [20]:
import numpy as np

In [21]:
sent_length = 5
embedded_docs = pad_sequences(onehot_repr, padding='pre' , maxlen = sent_length)
print(embedded_docs)

[[    0   633  5093 11577  4266]
 [    0   633  5093 11577  9303]
 [    0   633 10095 11577  5810]
 [    0  3645   913  4036  9932]
 [ 3645   913  4036  5461  8984]
 [10943   633  7436 11577  4424]
 [    0  5310 10730  3755  4036]]


In [22]:
dim = 30

In [27]:
model = Sequential()
model.add(Embedding(voc_size,30,input_length = sent_length))
# Compile with adam optimizer considering performance matrix as mean square error
model.compile('adam' ,'mse')

In [28]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 5, 30)             360000    
                                                                 
Total params: 360,000
Trainable params: 360,000
Non-trainable params: 0
_________________________________________________________________


In [29]:
print(model.predict(embedded_docs))

1/1 [==============================] - 1s 641ms/step
[[[-0.03836167 -0.02991678  0.01811231 ... -0.00275028 -0.03861245
   -0.00599531]
  [-0.01570177 -0.02759122 -0.04129822 ...  0.03040493 -0.01195548
   -0.00724189]
  [-0.00871162  0.01186261  0.03533195 ... -0.00714116 -0.03881643
    0.04485709]
  [ 0.04629821  0.02883971 -0.04074484 ...  0.04854156  0.01464453
    0.03826808]
  [ 0.03943816  0.0332404  -0.03249292 ... -0.02140664  0.03431867
    0.02755079]]

 [[-0.03836167 -0.02991678  0.01811231 ... -0.00275028 -0.03861245
   -0.00599531]
  [-0.01570177 -0.02759122 -0.04129822 ...  0.03040493 -0.01195548
   -0.00724189]
  [-0.00871162  0.01186261  0.03533195 ... -0.00714116 -0.03881643
    0.04485709]
  [ 0.04629821  0.02883971 -0.04074484 ...  0.04854156  0.01464453
    0.03826808]
  [ 0.03553515  0.01340866 -0.01283343 ...  0.04653115 -0.02821561
    0.03430036]]

 [[-0.03836167 -0.02991678  0.01811231 ... -0.00275028 -0.03861245
   -0.00599531]
  [-0.01570177 -0.02759122 -0.

In [30]:
embedded_docs[0]

array([    0,   633,  5093, 11577,  4266], dtype=int32)

In [31]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 26ms/step
[[-3.83616686e-02 -2.99167763e-02  1.81123056e-02 -4.40522432e-02
  -1.66806355e-02 -1.59666687e-03  8.20271671e-05  3.53075005e-02
   1.31750107e-03  4.93023060e-02  5.68435341e-03  3.99969928e-02
  -3.70465294e-02 -1.85638182e-02 -1.24738589e-02  4.65615280e-02
  -4.15065289e-02  4.35640849e-02  2.67992355e-02 -9.65422392e-03
   7.58133829e-04  1.53679885e-02  2.24601068e-02  2.12391727e-02
   3.46394069e-02 -4.72299717e-02 -1.76594146e-02 -2.75027752e-03
  -3.86124477e-02 -5.99531084e-03]
 [-1.57017708e-02 -2.75912173e-02 -4.12982218e-02  1.72060393e-02
  -1.49004944e-02 -8.04513693e-03  3.43957059e-02  9.50581953e-03
  -5.27601317e-03 -1.69871338e-02 -3.60412225e-02 -4.14011963e-02
   1.45757832e-02  4.10573371e-02 -2.95597203e-02 -2.86879782e-02
   3.40662114e-02 -3.55967656e-02  4.30778302e-02  4.52372096e-02
  -3.52299437e-02 -2.32367758e-02  2.47546919e-02  1.80304982e-02
   1.42463110e-02  3.31087969e-02  2.01891996e-02  3.04